src/experimental/NoisyCircuits.jl
Previously, the noise applied to branches in the perturbative expansion strategy traces the trajectory by ignoring branches having more errors than the maximum order. This led to the total probability being <1 when the order was less than the maximum order. This commit implements an alternative method of approximation where a branch is terminated when the number of errors applied in that branch reaches the maximum order limit. This should lead to the total probability being 1.
The previous version of the trajectory allows one to estimate the amount of approximation, that is related to the number of branches ignored, by calculating how far the total probability is, from 1. This option is missing in the new approach.
=> Feature: alternative approach to perturbative trajectories

src/randoms.jl
Use @inbounds to improve performance a bit.
Use Tuple (0,1) rather than range 0:1.
Using small Tuples rather than Arrays or other types often gives a
performance increase.
With this PR, for 200x200 Matrix{Int8}, fill_tril is more than twice as fast.
=> Improve performance of fill_tril

src/QuantumClifford.jl, src/randoms.jl
resolves #49
I added a helper function `sample_geometric_2` to sample a random number with respect to the desired distribution.
I removed the three versions of `quantum_mallows_int`, `quantum_mallows_float`, and `quantum_mallows_bigint` since they were almost identical (except for the random number generation for which I used the `sample_geometric_2` function).
=> DRY out quantum_mallows function

src/symbolic_cliffords.jl
Now the compiler can predict the type of the output based on the type of input. Previously we passed `Tm` type as a function argument. Since the compiler did not have any information about `Tm` it used to result in output type of those functions becoming `Any` in compile time
=> fix getshift, getmask, getbigindex type instability

CHANGELOG.md, benchmark/benchmarks.jl, ext/QuantumCliffordQuantikzExt/QuantumCliffordQuantikzExt.jl, src/affectedqubits.jl, src/misc_ops.jl, src/pauli_frames.jl, src/sumtypes.jl
Now compactification works for more types. In particular see these examples of things that previously could not be compactified:
```
using Revise
using QuantumClifford
using BenchmarkTools
function x_diag_circuit_noisy_measurement(csize)
circuit = []
for i in 1:csize
push!(circuit, PauliError(i, 0.1))
push!(circuit, sHadamard(i))
push!(circuit, sCNOT(i, csize+1))
push!(circuit, sMZ(csize+1,i))
push!(circuit, ClassicalXOR(1:(i%6+2),i))
end
return circuit
end
@benchmark pftrajectories(state,circuit) setup=(state=PauliFrame(1000, 1001, 1001); circuit=x_diag_circuit_noisy_measurement(1000)) evals=1
BenchmarkTools.Trial: 1126 samples with 1 evaluation.
Range (min … max):  3.532 ms …  4.088 ms  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     3.573 ms              ┊ GC (median):    0.00% …
```
=> support compactifications of more sophisticated types

src/misc_ops.jl, src/pauli_frames.jl, src/sumtypes.jl
```
function x_diag_circuit_noisy_measurement(csize)
circuit = []
for i in 1:csize
push!(circuit, PauliError(i, 0.1))
push!(circuit, sHadamard(i))
push!(circuit, sCNOT(i, csize+1))
push!(circuit, sMZ(csize+1,i))
push!(circuit, ClassicalXOR((1,(i%6+6)),i))
end
return circuit
end
@benchmark pftrajectories(state,circuit) setup=(state=PauliFrame(1000, 1001, 1001); circuit=compactify_circuit(x_diag_circuit_noisy_measurement(1000))) evals=1
Before:
BenchmarkTools.Trial: 10 samples with 1 evaluation.
Range (min … max):  2.885 ms …  2.962 ms  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     2.900 ms              ┊ GC (median):    0.00%
Time  (mean ± σ):   2.912 ms ± 30.387 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%
█▁ ▁   ▁      ▁    ▁                       ▁          ▁  ▁ …
```
=> Fix type instabilities in compactified methods

CHANGELOG.md, Project.toml, src/QuantumClifford.jl, src/symbolic_cliffords.jl, test/test_symcliff.jl
Functionality that we want 
```
julia> inv_op = inv(SingleQubitOperator(sHadamard(1)))
sHadamard on qubit 1
X₁ ⟼ + Z
Z₁ ⟼ + X
julia> expected_inv_op = sHadamard(1)
sHadamard on qubit 1
X₁ ⟼ + Z
Z₁ ⟼ + X
julia> inv(sHadamard(1))
sHadamard on qubit 1
X₁ ⟼ + Z
Z₁ ⟼ + X
```
I will add the twoqubit invs today as well.  Hope you find this plausible!
=> `inv` implementation for `SingleQubitOperator`

src/linalg.jl
This PR aims to introduce `doctests` for `tensor` methods and `inv` in the `linalg.jl`. This will help users in using these methods which might go unnoticed.  I am looking for your feedback and comments! Thanks for your help reviewing the PR!
=> introducing `doctests` for `tensor` methods and `inv`

src/enumeration.jl, test/test_enumerate.jl
This PR aims to improve the `doctests` of  `enumeration.jl`. In the formula, there was a minor issue as well that `nn` was repeated twice` 2ⁿⁿΠⱼ₌₁ⁿ(4ʲ-1)` . It is (2)^(n^2) in the paper.  Also, added a small test!
Thank you for your help reviewing the PR.
=> improving `doctests` for `Enumeration.jl`

.github/workflows/ci.yml, test/runtests.jl, test/test_bitpack.jl
Some of our Python optional extensions (the ldpc python package) seem to fail to install on some mac systems. Adding CI for mac on x64 and arm.
@amicciche
=> CI on ARM Mac

src/QuantumClifford.jl, src/dense_cliffords.jl, src/ecc/ECC.jl, src/ecc/decoder_pipeline.jl, src/sumtypes.jl, test/test_jet.jl
Thanks for the JET simplification. Let's reduce it a bit further to 15 :)
The `fast_row` and `quantum_mallows` were not visible locally, so that's why locally it showed `17` but `nightly `showed it `19`.
- [na] Substantial new functionality is documented within the docs.
=> Reduces JET errors

src/nonclifford.jl, test/test_nonclifford_quantumoptics.jl
All the tests in `noncliffordquantumoptics.jl `should pass now.
**Please address only one topic or issue per pull request! Many small PRs are much easier to review and merge than one large PR.**
Before merging, all changes and new functionality should be marked in the CHANGELOG file, but feel free to just leave your CHANGELOG notes in the PR description, to avoid merge conflicts with other requests modifying that file. The maintainer will add these CHANGELOG notes for you if you do so.
Before considering your pull request ready for review and merging make sure that all of the following are completed (please keep the clecklist …
=> noncliff: fixes `expect`

src/QuantumClifford.jl, test/test_throws.jl
Closes #208
**Please address only one topic or issue per pull request! Many small PRs are much easier to review and merge than one large PR.**
Before merging, all changes and new functionality should be marked in the CHANGELOG file, but feel free to just leave your CHANGELOG notes in the PR description, to avoid merge conflicts with other requests modifying that file. The maintainer will add these CHANGELOG notes for you if you do so.
Before considering your pull request ready for review and merging make sure that all of the following are completed (please keep the clecklist as part of your PR):
With regard to Task 5, there was …
=> fixes #208: Constructing only valid Stabilizer(phases, xs, zs)

src/nonclifford.jl, test/test_jet.jl
This PR aims to make sure there are no JET caused by `nonclifford.jl`. There were 3 JET masquerading as 1 JET error caused by using `zip(pc.paulis, pc.weights)` in three `for` loops related to `PauliChannel`.  The fix does remove these JET errors, I have cross verified it running JET.
=> noncliff: fix JET errors

ext/QuantumCliffordLDPCDecodersExt/QuantumCliffordLDPCDecodersExt.jl, ext/QuantumCliffordPyQDecodersExt/QuantumCliffordPyQDecodersExt.jl, src/ecc/decoder_pipeline.jl
This PR is about removing the performance detriments because of allocations introduced by `vcat` and `hcat` in the decoders. In addition, `evaluate_guesses` is also made allocation free. Attempt is made to improve the `decode` and `batchdecode` as well. Instead of unnecessary copying, `@view`  has been used. I have also checked this there is not any JET errors introduced as well. Resource: [Performance Tips](https://docs.julialang.org/en/v1/manual/performance-tips/) guide for better understanding of the context. 
...
=> some performance optimizations in decoders

src/nonclifford.jl, test/test_nonclifford_quantumoptics.jl
Improving `dictvaltype` and `apply!`. 
**Please address only one topic or issue per pull request! Many small PRs are much easier to review and merge than one large PR.**
Before merging, all changes and new functionality should be marked in the CHANGELOG file, but feel free to just leave your CHANGELOG notes in the PR description, to avoid merge conflicts with other requests modifying that file. The maintainer will add these CHANGELOG notes for you if you do so.
Before considering your pull request ready for review and merging make sure that all of the following are completed (please keep the clecklist as part of your PR):
If …
=> noncliff: improvements to `apply!` and `dictvaltype`

src/symbolic_cliffords.jl
The current phase formula for `sInvZCrY` is quite long and ugly. My bad. It can be made minimal and simple which is the aim of this short PR. 
Sorry for this sudden PR, @Krastanov! Thank you!
...
**Please address only one topic or issue per pull request! Many small PRs are much easier to review and merge than one large PR.**
Before merging, all changes and new functionality should be marked in the CHANGELOG file, but feel free to just leave your CHANGELOG notes in the PR description, to avoid merge conflicts with other requests modifying that file. The maintainer will add these CHANGELOG notes for you if you do so.
Before …
=> use minimal form phase for sInvZCrY

CHANGELOG.md, Project.toml, ext/QuantumCliffordHeckeExt/QuantumCliffordHeckeExt.jl, ext/QuantumCliffordHeckeExt/lifted.jl, ext/QuantumCliffordHeckeExt/lifted_product.jl, ext/QuantumCliffordHeckeExt/types.jl, test/test_ecc_base.jl, test/test_ecc_codeproperties.jl, test/test_ecc_decoder_all_setups.jl
@royess , it seems the tests in your PR were never actually running. Part of them were missing because the dictionary of codes was not set properly (you entered the public function as a key instead of the private type). Part of them were not enabled because they were pasted outside of the testitem definition.
These two issues are now fixed, but that led to actually having errors in the PR, partially due to the fix to the piracy issue that the PR had introduced.
Could you look into this sometime soon? In particular, (1) given how you are using the lift function, maybe we can completely drop the `repr::Function` and just rely on Nemo/Hecke; (2) we need a fix for the adjoint piracy (potentially having this upstreamed).
=> enable Lifted Product Code tests and reintroduce piracy

CHANGELOG.md, Project.toml, ext/QuantumCliffordHeckeExt/lifted_product.jl, ext/QuantumCliffordHeckeExt/types.jl, test/test_ecc_base.jl, test/test_ecc_decoder_all_setups.jl
In this PR, the adjoint piracy is removed, which is related to #371 .
After this removal, an inner function `group_algebra_conj` is used in favor of reloading `Base.adjoint`. Some comments are also updated and corrected.
=> fix incompatibility with Julia 1.11.1 and remove the adjoint piracy

.github/workflows/ci.yml
After clogging the CI queue with many small commits in #400, I noticed that intermediate builds for pull requests are not cancelled. This fixes it.
@Krastanov If you want this, I can also add it to the other *.yml files.
=> ci: tweak ci.yml

src/nonclifford.jl
This PR aims too improve the performance of  `_allthreesumtozero`. Benchmarks are attached below: 
As  you mentioned some time ago, to prevent from falling into trap of misleading results, I used `evals = 1` and `setups`
Benchmarks:
```
julia> using BenchmarkTools
julia> function _allthreesumtozero(a, b, c)
@inbounds @simd for i in 1:length(a)
iseven(a[i] + b[i] + c[i]) || return false
end
true
end
julia> N = 10^6;
julia> a = rand(1:100, N);
julia> b = rand(1:100, N);
julia> c = rand(1:100, N);
julia> @benchmark _allthreesumtozero($a, $b, $c) evals=1 setup=(a_copy=copy(a); b_copy=copy(b); c_copy=copy(c))
BenchmarkTools.Trial: 633 samples with 1 evaluation.
Range (min … max):  330.000 ns …  19.116 μs  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     943.000 ns               ┊ GC …
```
=> noncliff:  improve performance of  `_allthreesumtozero`

src/nonclifford.jl, test/test_throws.jl
This PR aims to improve the error handling for `apply!(sm, pcT)`. 
Before:
```
julia> p = embed(2, 1, pcT)
A unitary Pauli channel P = ∑ ϕᵢ Pᵢ with the following branches:
with ϕᵢ | Pᵢ
0.853553+0.353553im | + __
0.146447-0.353553im | + Z_
julia> sm = GeneralizedStabilizer(S"X")
A mixture ∑ ϕᵢⱼ Pᵢ ρ Pⱼ† where ρ is
𝒟ℯ𝓈𝓉𝒶𝒷
+ Z
𝒮𝓉𝒶𝒷
+ X
with ϕᵢⱼ | Pᵢ | Pⱼ:
1.0+0.0im | + _ | + _
julia> apply!(sm, p)
ERROR: BoundsError: attempt to access 2×1 view(::Matrix{UInt64}, :, 2:2) with eltype UInt64 at index [1:2, 2]
Stacktrace:
[1] throw_boundserror(A::SubArray{UInt64, 2, Matrix{…}, Tuple{…}, true}, I::Tuple{Base.Slice{…}, Int64})
@ Base ./abstractarray.jl:737
[2] checkbounds
@ ./abstractarray.jl:702 [inlined]
[3] view
@ ./subarray.jl:184 [inlined]
...
Some type information was truncated. Use …
```
=> noncliff: improve error handling in `apply!(sm, pcT)`

src/nonclifford.jl, test/test_nonclifford_quantumoptics.jl
This PR is inspired from this comment: https://github.com/QuantumSavory/QuantumClifford.jl/pull/355#discussion_r1826568457
=> noncliff: add copy, == for GeneralizedStabilizer, UnitaryPauliChannel

src/nonclifford.jl, test/test_nonclifford_quantumoptics.jl
This PR removes the TODO comment and add tests for conjugation. This PR is inspired from this comment: https://github.com/QuantumSavory/QuantumClifford.jl/pull/408#issuecomment-2452981604
=> noncliff: add tests for conjugate destabs

docs/src/references.bib, ext/QuantumCliffordHeckeExt/lifted_product.jl, test/test_ecc_2bga.jl
This PR reproduces the entire Table 2 results of https://arxiv.org/pdf/2306.16400 using the Direct Product of Groups. The goal is twofold: demonstrate a new functionality via Direct Product of Abelian Groups using `Hecke` and crosscheck it via reproducing all the results from Table 2. 
Table 2 whose results are reproduced:
=> add tests and examples of  Cₘ × C₂ 2BGA codes

src/nonclifford.jl
This PR sets up the scaffolding for `projectrand!` in `GeneralizedStabilizer`, inspired by comments in #355. The goal is to provide clear, well-documented code for readers unfamiliar with the original paper.
I think the work for `projectrand!` can be divided into the following portions. Work for `define _proj` and basic tests is underway in #355, and the #418 is being investigated. Segmenting the work in this modular way facilitates future additions and modifications, while also preventing confusion by isolating distinct components.
```mermaid
graph TD
%% Define subgraph for scaffolding
subgraph ScaffoldingBranch [ ]
direction TB
B[Scaffolding] --> B1[convert expectation to prob <br> randomly choose projection]
end
A[projectrand!] --> B
A --> C[Nitty Gritty]
C --> C1[define_proj]
A --> …
```
=> noncliff: scaffolding for projectrand! for GeneralizedStabilizer

ext/QuantumCliffordHeckeExt/lifted_product.jl, test/test_doctests.jl
This PR implements minor fixes in doctests.
Edit:
=> fix: broken doctests and typos

CHANGELOG.md, Project.toml, src/randoms.jl
This commit improves the performance of the unbiased branch of `random_pauli!` by a factor of about 100. Each chunk in the data array is replaced with a random `UInt64`.
Before:
```julia
julia> @time random_pauli(10^9);
9.596375 seconds (5 allocations: 238.419 MiB, 0.06% gc time)
```
After:
```julia
julia> @btime random_pauli(10^9);
74.858 ms (5 allocations: 238.42 MiB)
```
Note:
I included code to unset the noncoding bits in the `xz` field of `PauliOperator`. Similar code may already exist somewhere. But I did not find it.
I was unable to find information on details of code formatting.
-------------------
**Please address only …
=> Improve performance of random_pauli! by 100x

README.md
This PR aims to fix the broken links to the stab manual on `ReadMe` page. I have checked the hyperlinks by clicking on the words that threw error before, now they land to the correct place in the manual. The problem seemed to be outdated links that caused the error.
Please help review the PR, Thanks so much!
=> fix: broken links to the stab manual on `ReadMe`

ext/QuantumCliffordMakieExt/QuantumCliffordMakieExt.jl, test/test_allocations.jl
This PR aims to fix the `ArgumentError` when using functions from `QuantumCliffordMakieExt` module that now occurs on CI as CI Documentation error. It causes all the `@example` blocks to fail that calls the `stabilizerplot_axis`. The following stack trace on CI is the following for all example blocks that throw error:
```julia
Error: failed to run `@example` block in src/canonicalization.md:16-21
@example
using QuantumClifford, CairoMakie
f=Figure()
stabilizerplot_axis(f[1,1], canonicalize!(random_stabilizer(20,30)))
f
exception = 
ArgumentError: component type FixedPointNumbers.N0f8 is an 8-bit type representing 256 values from 0.0 to 1.0,
but the values (0x001b9e77, 0x001b9e77, 0x001b9e77) do not lie within this range.
See the READMEs for FixedPointNumbers and ColorTypes for more …
```
=> fix: `RGB` color initialization in `QuantumCliffordMakieExt` colormap

test/test_cliff.jl, test/test_nonclifford_quantumoptics.jl, test/test_stabcanon.jl
This PR removes uncessary `using` and fix deprecation warnings in `test/` folder. Should be straightforward to review.
=> chore: fix deprecation warnings and remove unused imports in tests

ext/QuantumCliffordJuMPExt/min_distance_mixed_integer_programming.jl, src/ecc/ECC.jl
This PR aims to removes the `upper_bound` parameter from the MIP distance solver because it conflicts with the algorithm’s design. The solver introduced in [arXiv:1108.5738](https://arxiv.org/abs/1108.5738) implements an exact minimum distance calculation formulated as the binary integer program:
```math
\begin{aligned}
&\min \sum_v x_v \
&\text{s.t. } \bigoplus_{v\in f} x_v = s_f \quad \forall f \
&x_v \in {0,1}
\end{aligned}
```
Attempting to repurpose it for upper bounds computation introduced unreliable heuristics. Empirical testing revealed the `upper_bound` mode produced inconsistent results. This change restores the solver’s single purpose:  compute the true minimum distances.
TODO: For rigorous upper bounds computation, dedicated algorithms such as random information set in …
=> remove unreliable `upper_bound` from mip distance solver

CHANGELOG.md, src/project_trace_reset.jl, test/test_projections.jl
Fixes #492. Now auto converts states on projectX/Y/Z!. Added relevant tests.
=> fix: single qubit projection now takes Stabilizer

ext/QuantumCliffordGPUExt/apply_noise.jl
I am surprised this has lasted for two years without being detected/fixed, perhaps due to lack of GPU testing? I kept getting failures when running my own local CUDA tests and it appears that at one point in time someone removed the line `stab = frame.frame` but forgot to edit the rest of the file.
Did not update the changelog, unaware if extensions are to be included within it.
=> Resolve missing identifier in GPUExt

src/QuantumClifford.jl, src/graphs/graphs.jl, src/symbolic_cliffords.jl, test/test_graphs.jl
This PR targets the following project items:
1. [Type for graph state](https://github.com/orgs/QuantumSavory/projects/12?pane=issue&itemId=109344961). I plan to implement the graph backend parameterization in the next PR involving interface.
2. [Conversion between graph states and Stabilizer](https://github.com/orgs/QuantumSavory/projects/12?pane=issue&itemId=109345027)
It gives
- a cleaner API on graph states through `GraphState` type
- updated tests and docs accordingly
Help/comment is appreciated on documentation as it's my first time writing/changing them. Also I wonder why the `doctest` is disabled?
Before considering your pull request ready for review and merging make sure that all of the following are completed (please keep the clecklist as part of your PR):
=> add: `GraphState` type

src/misc_ops.jl, test/test_noisycircuits.jl
- Changed part of the implementation for applywstatus! for VerifyOp.
- previously the only operation done on the input register was a canonicalize_rref!
- now we use traceout! as well before canonicalizing
- Changed the part of applywstatus! for verifyOp which checks for size mismatch of input tableau to the struct of verifyop instead. Created an inner constructor for this purpose
- Wrote a test which shows the working functionality(this test would have failed previously)
=> Fix edge-case comparisons in VerifyOp

.buildkite/pipeline.yml, ext/QuantumCliffordHeckeExt/QuantumCliffordHeckeExt.jl, ext/QuantumCliffordHeckeExt/lifted_product.jl, ext/QuantumCliffordOscarExt/d_dimensional_codes.jl, src/ecc/ECC.jl, src/ecc/codes/concat.jl, src/ecc/codes/random_circuit.jl, test/runtests.jl, test/test_ecc.jl, test/test_ecc_2bga.jl, test/test_ecc_base.jl, test/test_ecc_bch.jl, test/test_ecc_bivaraite_bicycle_as_twobga.jl, test/test_ecc_codeproperties.jl, test/test_ecc_coprime_bivaraite_bicycle.jl, test/test_ecc_d_dimensional_codes.jl, test/test_ecc_decoder_all_setups.jl, test/test_ecc_encoding.jl, test/test_ecc_generalized_bicycle_codes.jl, test/test_ecc_generalized_bicycle_codes_slow.jl, test/test_ecc_generalized_hypergraph_product.jl, test/test_ecc_generalized_toric_codes.jl, test/test_ecc_lacross.jl, test/test_ecc_lpcode_simpler_repr.jl, test/test_ecc_minimum_distance.jl, test/test_ecc_multivariate_bicycle.jl, test/test_ecc_naive_syndrome.jl, test/test_ecc_syndromes.jl, test/test_ecc_throws.jl, test/test_ecc_trivariate_tricycle.jl
This PR enhances the `all_testable_code_instances` function to handle code instantiation of codes implemented in the `QuantumCliffordOscarExt`. Many advanced QECCs  such as TrivariateTricycle codes, and various homological product codes from the `QuantumCliffordOscarExt` were not instantiated by the `all_testable_code_instances` function when utilizing `code_instance_args` for the full spectrum of tests including measurements and decoding similar to what is done for `test_ecc_two_bga` codes in `test_ecc_base.jl`. 
The function now dynamically instantiates all available code types (including those from loaded extensions) and tries to instantiate them with their predefined parameters from the `code_instance_args`. If Oscar is used in CI, the `code_instance_args` is the merge of two …
=> tests: make all_testable_code_instances extension-aware
